### ISSUE TITLE
check total_supply in collect_fee

### ISSUE THREAD

**Issue by zjb0807** [nutsfinance/stable-asset#41]
https://github.com/nutsfinance/stable-asset/blob/0505e4f73ac387d3f82db2bdcc0893c70b80713f/lib/stable-asset/src/lib.rs#L1419-L1428

@ukby1234 Can we check the `old_total_supply` and `total_supply` are same here?  cc @xlc

**Comment by ukby1234** [comment]
@zjb0807 I don't think it's necessary. The `old_total_supply ` and `total_supply ` is a result from the `get_pending_fee_amount`, which I just did a patch to apply a `1%` max slippage.
